unittests_task:
  container:
    image: $ELECTRUM_IMAGE
    cpu: 1
    memory: 1G
  matrix:
    - name: "unittests: Python $ELECTRUM_PYTHON_VERSION"
      env:
        ELECTRUM_IMAGE: python:$ELECTRUM_PYTHON_VERSION
      matrix:
        - env:
            ELECTRUM_PYTHON_VERSION: 3.8
        - env:
            ELECTRUM_PYTHON_VERSION: 3.10
        - env:
            ELECTRUM_PYTHON_VERSION: 3.12
  submodules_script:
    - git submodule init
    - git submodule update
  version_script:
    - python3 --version
  install_script:
    - pip install pytest-cov
    # TODO cache building libsecp .so, which is done implicitly in the next step:
    - pip install .
  script:
    - pytest --cov=electrum_ecc
